package pojo;
// Generated Oct 2, 2018 12:18:12 PM by Hibernate Tools 4.3.1


import dao.AdminDAO;
import dao.ContactUsDAO;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 * Admin generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class Admin  implements java.io.Serializable {


     private Integer adminId;
     private String adminName;
     private String adminEmail;
     private String adminContact;
     private String adminUsername;
     private String adminPassword;
     private String adminStatus;
     private Set services = new HashSet(0);
     private Set crews = new HashSet(0);
     
     private String msg;
    private List<Admin> listMhs;
    private int selectedID;

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public Admin() {
    }

	
    public Admin(String adminName, String adminEmail, String adminContact, String adminUsername, String adminPassword, String adminStatus) {
        this.adminName = adminName;
        this.adminEmail = adminEmail;
        this.adminContact = adminContact;
        this.adminUsername = adminUsername;
        this.adminPassword = adminPassword;
        this.adminStatus = adminStatus;
    }
    public Admin(String adminName, String adminEmail, String adminContact, String adminUsername, String adminPassword, String adminStatus, Set services, Set crews) {
       this.adminName = adminName;
       this.adminEmail = adminEmail;
       this.adminContact = adminContact;
       this.adminUsername = adminUsername;
       this.adminPassword = adminPassword;
       this.adminStatus = adminStatus;
       this.services = services;
       this.crews = crews;
    }
   
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }
    public String getAdminEmail() {
        return this.adminEmail;
    }
    
    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }
    public String getAdminContact() {
        return this.adminContact;
    }
    
    public void setAdminContact(String adminContact) {
        this.adminContact = adminContact;
    }
    public String getAdminUsername() {
        return this.adminUsername;
    }
    
    public void setAdminUsername(String adminUsername) {
        this.adminUsername = adminUsername;
    }
    public String getAdminPassword() {
        return this.adminPassword;
    }
    
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }
    public String getAdminStatus() {
        return this.adminStatus;
    }
    
    public void setAdminStatus(String adminStatus) {
        this.adminStatus = adminStatus;
    }
    public Set getServices() {
        return this.services;
    }
    
    public void setServices(Set services) {
        this.services = services;
    }
    public Set getCrews() {
        return this.crews;
    }
    
    public void setCrews(Set crews) {
        this.crews = crews;
    }


    public void cleardata(){
        this.adminId = 0;
        this.adminName = null;
        this.adminUsername = null;
        this.adminPassword = null;
        this.adminContact = null;
        this.adminStatus = null;
    }

    public String validateLogin(){
        AdminDAO adm = new AdminDAO();
        boolean validate = adm.validateLogin(this);
        if (validate==true) {
            this.setMsg(null);
            cleardata();
            return "Table-Contactus?faces-redirect=true"; 
        }else{
            this.setMsg("The username or password you entered is incorrect, or your account has been disabled.");
            return "index?faces-redirect=true";
        }
    }

    
    

}

