package pojo;
// Generated Sep 27, 2018 2:24:53 PM by Hibernate Tools 4.3.1

import dao.ContactUsDAO;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;




/**
 * Contactus generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class Contactus  implements java.io.Serializable {


     private Integer contactId;
     private String contactName;
     private String contactEmail;
     private String contactMessage;
     private String msg;
     private Integer selectedID;
     private List<Contactus> listMhs;

    public Integer getSelectedID() {
        return selectedID;
    }

    public void setSelectedID(Integer selectedID) {
        this.selectedID = selectedID;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public Contactus() {
    }

    public Contactus(String contactName, String contactEmail, String contactMessage) {
       this.contactName = contactName;
       this.contactEmail = contactEmail;
       this.contactMessage = contactMessage;
    }
   
    public Integer getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    public String getContactEmail() {
        return this.contactEmail;
    }
    
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }
    public String getContactMessage() {
        return this.contactMessage;
    }
    
    public void setContactMessage(String contactMessage) {
        this.contactMessage = contactMessage;
    }
    
    public void cleardata(){
        this.contactId = null;
        this.contactName = null;
        this.contactEmail = null;
        this.contactMessage = null;
    }

    public void simpanData(){
            ContactUsDAO kryDAO = new ContactUsDAO();
            kryDAO.nambah(this);
            this.msg = "Message Has Been Sent";
            cleardata();
        }

    public List<Contactus> lihatDataContactUs()
    {
        this.msg = null;
        ContactUsDAO mhsDao = new ContactUsDAO();
        listMhs = mhsDao.getAllContactUs();
        return listMhs;   
    }
    
    public List<Contactus> getAllIDContactUs()
    {
        ContactUsDAO mhsDao = new ContactUsDAO();
        listMhs = mhsDao.getIDContactUs();
        return listMhs;
    }
    
    public void ambilContacUsByID()
    {
        ContactUsDAO mhsDao = new ContactUsDAO();
        List<Contactus> ls = mhsDao.getContactUsByID(selectedID);
        
        this.contactId = ls.get(0).contactId;
        this.contactName = ls.get(0).contactName;
        this.contactEmail = ls.get(0).contactEmail;
        this.contactMessage = ls.get(0).contactMessage;
    }
    
    public void updateMahasiswa()
    {
        ContactUsDAO mhsDao = new ContactUsDAO();
        mhsDao.updateMahasiswa(this);
        this.msg = "Berhasil mengubah data mahasiswa..";
        this.cleardata();
    }
    
    public void deleteMahasiswa()
    {
        ContactUsDAO mhsDao = new ContactUsDAO();
        mhsDao.deleteMahasiswa(this);
        this.msg = "Berhasil menghapus data mahasiswa..";
        this.cleardata();
    }

}


