package pojo;
// Generated Oct 2, 2018 12:18:12 PM by Hibernate Tools 4.3.1

import dao.ServiceDAO;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Transient;
import javax.servlet.http.Part;




/**
 * Service generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class Service  implements java.io.Serializable {

    public Part getImage() {
        return image;
    }

    public void setImage(Part image) {
        this.image = image;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public List<Service> getListMhs() {
        return listMhs;
    }

    public void setListMhs(List<Service> listMhs) {
        this.listMhs = listMhs;
    }


     private Integer serviceId;
     private Integer admin;
     private String serviceName;
     private String serviceImage;
     private String serviceDesc;
     private Integer selectedID;
     
     
     @Transient
     private Part image;
    
     
     private String msg;
    private List<Service> listMhs;

    public Service() {
    }

    public Service(Integer admin, String serviceName, String serviceImage, String serviceDesc) {
       this.admin = admin;
       this.serviceName = serviceName;
       this.serviceImage = serviceImage;
       this.serviceDesc = serviceDesc;
    }
   
    public Integer getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }
    public Integer getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Integer admin) {
        this.admin = admin;
    }
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }
    public String getServiceImage() {
        return this.serviceImage;
    }
    
    public void setServiceImage(String serviceImage) {
        this.serviceImage = serviceImage;
    }
    public String getServiceDesc() {
        return this.serviceDesc;
    }
    
    public void setServiceDesc(String serviceDesc) {
        this.serviceDesc = serviceDesc;
    }

    public String doUpload() {
		String path = null;
		String pathValue = null;
		try {
			InputStream in = image.getInputStream();
			File f = new File("C:\\Users\\Windows 10 Pro\\Documents\\NetBeansProjects\\obat_pijat\\web\\images\\"+image.getSubmittedFileName());
			f.createNewFile();
			FileOutputStream out = new FileOutputStream(f);
			
			byte[] buffer = new byte[1024];
			int length;
			while ((length=in.read(buffer))>0){
				out.write(buffer, 0, length);
			}
			out.close();
			in.close();
			
			path = String.valueOf(f.getAbsolutePath());
			pathValue = "images\\"+image.getSubmittedFileName();
			System.out.println("upload success");
		} catch (Exception e) {
			System.out.println(e);
		}
		return pathValue;
	}
    
    public void addServicelist() {
		ServiceDAO dao = new ServiceDAO();
		setServiceImage(doUpload());
		dao.addNewService(this);
		cleardata();
	}
    
    public void cleardata(){
        serviceId = null;
        admin = null;
        serviceName = null;
        serviceImage = null;
        serviceDesc = null;
        
    }

    public List<Service> lihatDataCrew()
    {
        this.msg = null;
        ServiceDAO mhsDao = new ServiceDAO();
        listMhs = mhsDao.getAllService();
        return listMhs;   
    }
    
    public List<Service> getAllIDService()
    {
        ServiceDAO mhsDao = new ServiceDAO();
        listMhs = mhsDao.getIDService();
        return listMhs;
    }
    
    public void ambilServiceByID()
    {
        ServiceDAO mhsDao = new ServiceDAO();
        List<Service> ls = mhsDao.getServiceByID(getSelectedID());
        this.serviceId = ls.get(0).serviceId;
        this.admin = ls.get(0).admin;
        this.serviceName = ls.get(0).serviceName;
        this.serviceImage = ls.get(0).serviceImage;
        this.serviceDesc = ls.get(0).serviceImage;
    }
    
    public void updateMahasiswa()
    {
        ServiceDAO mhsDao = new ServiceDAO();
        mhsDao.updateMahasiswa(this);
        this.msg = "Data Has Been Updated";
        this.cleardata();
    }
    
    public void deleteMahasiswa()
    {
        ServiceDAO mhsDao = new ServiceDAO();
        mhsDao.deleteMahasiswa(this);
        this.msg = "Data Has Been Deleted";
        this.cleardata();
    }

    /**
     * @return the selectedID
     */
    public Integer getSelectedID() {
        return selectedID;
    }

    /**
     * @param selectedID the selectedID to set
     */
    public void setSelectedID(Integer selectedID) {
        this.selectedID = selectedID;
    }


}


